#!/usr/bin/env bash
#Install nginx on my server
#Nginx is listening on port 80

sudo apt-get -y update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
