#!/usr/bin/env bash
# Sets up a new 404 error page and configures Nginx

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create an "Hello World!" HTML file and move it to /var/www/html
echo "Hello World!" > index.html
sudo mv index.html /var/www/html

# Create a custom 404 error page with the string "Ceci n'est pas une page" and move it to /var/www/html
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html

# Define the Nginx server block configuration with a redirection from /redirect_me
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   
   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }
   
   error_page 404 /404.html;
   
   location = /404.html {
      internal;
   }
}" > default

# Overwrite the default Nginx server block configuration
sudo mv -f default /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
