#!/usr/bin/env bash
# This script installs Nginx and sets a custom header

# Updating package information
apt-get -y update

# Installing Nginx
apt-get -y install nginx

# Creating a simple Hello World page
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Creating a custom 404 error page
echo "Page not found indicator" > /usr/share/nginx/html/custom_404.html

# Configure Nginx with custom rules
cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    server_name _;

    location / {
        rewrite ^/redirect_me https://github.com/Tolulope05 permanent;
    }

    error_page 404 /custom_404.html;
    
    location = /custom_404.html {
        root /usr/share/nginx/html;
        internal;
    }

    add_header X-Served-By "$HOSTNAME";
}
EOL

# Adding custom header to the Nginx configuration
sed -i 's/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n    add_header X-Served-By "$HOSTNAME";/' /etc/nginx/nginx.conf

# Starting Nginx service
service nginx start
