#!/usr/bin/env bash
#installs and sets up haproxy
# Add HAProxy repository and install HAProxy
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-latest
apt-get -y update
apt-get install -y haproxy

# Enable HAProxy service
echo "ENABLED=1" > /etc/default/haproxy

# Configure HAProxy
echo "
listen load_balancer
  bind *:80
  mode http
  balance roundrobin
  option httpclose
  option forwardfor
  server 17272-web-01 44.200.83.158:80 check
  server 17272-web-02 3.237.16.226:80 check
" >> /etc/haproxy/haproxy.cfg

# Start HAProxy service
service haproxy start
