#!/usr/bin/env bash
#Installs and configures HAproxy on my lb-01 server.
apt-get update
apt-get install -y haproxy

# Configuring HAProxy
cat <<EOL > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend web-frontend
    bind *:80
    mode http
    default_backend web-servers

backend web-servers
    balance roundrobin
    server web-01 268587-web-01:80 check
    server web-02 268587-web-02:80 check
EOL

# Enabling HAProxy init script
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Starting HAProxy service
service haproxy start

# Ensuring HAProxy starts on boot
update-rc.d haproxy defaults
