#!/usr/bin/env bash

# Install HAProxy
apt-get update
apt-get install -y haproxy

# Configure HAProxy
cat <<EOL > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend web-frontend
    bind *:80
    mode http
    default_backend web-servers

backend web-servers
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOL

# Enable HAProxy init script
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Start HAProxy service
service haproxy start

# Ensure HAProxy starts on boot
update-rc.d haproxy defaults
