#!/usr/bin/env bash
# a Bash script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu.

private_key = "~/.ssh/school"
r_user = "ubuntu"
r_server = "41.204.187.5"

ssh -i $private_key $r_user@$r_server
