#!/usr/bin/env bash
# a Bash script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu.

private_key="~/.ssh/school"
r_user="ubuntu"
r_server="54.157.138.138"

ssh -i $private_key $r_user@$r_server
